//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.HackMD.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.HackMD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy publish link (Ctrl+C).
        /// </summary>
        internal static string context_copy_link {
            get {
                return ResourceManager.GetString("context_copy_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in both mode (Ctrl+Alt+B).
        /// </summary>
        internal static string context_open_both {
            get {
                return ResourceManager.GetString("context_open_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in edit mode (Ctrl+Alt+E).
        /// </summary>
        internal static string context_open_edit {
            get {
                return ResourceManager.GetString("context_open_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in view mode (Ctrl+Alt+V).
        /// </summary>
        internal static string context_open_view {
            get {
                return ResourceManager.GetString("context_open_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API token is not set.
        /// </summary>
        internal static string error_no_auth_token {
            get {
                return ResourceManager.GetString("error_no_auth_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change in settings.
        /// </summary>
        internal static string error_no_auth_token_desc {
            get {
                return ResourceManager.GetString("error_no_auth_token_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open HackMD notes.
        /// </summary>
        internal static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HackMD.
        /// </summary>
        internal static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API token.
        /// </summary>
        internal static string setting_api_token {
            get {
                return ResourceManager.GetString("setting_api_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Mode.
        /// </summary>
        internal static string setting_view_mode {
            get {
                return ResourceManager.GetString("setting_view_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string setting_view_mode_both {
            get {
                return ResourceManager.GetString("setting_view_mode_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view mode used with notes.
        /// </summary>
        internal static string setting_view_mode_desc {
            get {
                return ResourceManager.GetString("setting_view_mode_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string setting_view_mode_edit {
            get {
                return ResourceManager.GetString("setting_view_mode_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string setting_view_mode_view {
            get {
                return ResourceManager.GetString("setting_view_mode_view", resourceCulture);
            }
        }
    }
}
